# -*- coding: utf-8 -*-
"""nhom7_diembatthuong.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j-OnW1KIAAO0unlsLGpARj0_TtOng9Rm
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

# Tắt cảnh báo để hiển thị output gọn gàng hơn
warnings.filterwarnings('ignore')

# --- 1. Thiết lập Dữ liệu ---
file_name = 'Studentscore.csv'

# Đọc file CSV
try:
    df = pd.read_csv(file_name)
    print("✅ Đọc file thành công!")
except FileNotFoundError:
    print(f"❌ Lỗi: Không tìm thấy file {file_name}. Vui lòng đảm bảo file đã được tải lên.")
    exit()

# Các cột điểm cần phân tích Z-score
score_cols = ['TX1', 'TX2', 'TX3', 'GK', 'CK']
group_col = 'lop' # Cột được dùng để nhóm (phân loại theo lớp)
z_score_threshold = 2 # Ngưỡng xác định giá trị bất thường

# Kiểm tra sự tồn tại của các cột cần thiết
missing_cols = [col for col in score_cols + [group_col, 'MaHS'] if col not in df.columns]
if missing_cols:
    print(f"❌ Lỗi: Thiếu các cột quan trọng trong file: {', '.join(missing_cols)}")
    print("Vui lòng kiểm tra lại cấu trúc file CSV.")
    exit()

# --- 2. Hàm tính Z-score và Xác định Bất thường ---
def calculate_zscore_and_outlier(df, score_col, group_col, threshold=2):
    """Tính Z-score và xác định giá trị bất thường theo lớp cho một cột điểm."""

    # Hàm tính Z-score
    def zscore_func(series):
        std_dev = series.std()
        # Tránh chia cho 0
        if std_dev == 0:
            return 0
        return (series - series.mean()) / std_dev

    # Áp dụng tính Z-score theo từng nhóm (lop)
    z_score_col = f'Z_{score_col}'
    df[z_score_col] = df.groupby(group_col)[score_col].transform(zscore_func)

    # Xác định Bất thường
    outlier_col = f'Is_Outlier_{score_col}'
    df[outlier_col] = np.where(np.abs(df[z_score_col]) > threshold, 'Bất thường', 'Bình thường')

    return df, z_score_col, outlier_col

# --- 3. Thực hiện tính toán cho TẤT CẢ các bài kiểm tra ---
results_data = []

for col in score_cols:
    df, z_col_name, outlier_col_name = calculate_zscore_and_outlier(df, col, group_col, z_score_threshold)

    # Tổng hợp dữ liệu số lượng học sinh bất thường để trực quan hóa
    outlier_counts = df.groupby(group_col)[outlier_col_name].value_counts().unstack(fill_value=0).reset_index()

    # Lấy số lượng Bất thường và thêm cột tên bài kiểm tra
    if 'Bất thường' in outlier_counts.columns:
        outlier_counts = outlier_counts[[group_col, 'Bất thường']]
        outlier_counts.columns = [group_col, 'Count']
        outlier_counts['Test'] = col
        results_data.append(outlier_counts)

# Gộp tất cả kết quả vào một DataFrame duy nhất để vẽ biểu đồ
if results_data:
    final_plot_df = pd.concat(results_data, ignore_index=True)
    print("\n✅ Hoàn thành tính toán Z-score và xác định bất thường cho tất cả bài kiểm tra.")
else:
    print("\n❌ Lỗi: Không có dữ liệu để tổng hợp cho biểu đồ.")
    exit()

# --- 4. Trực quan hóa bằng Biểu đồ Cột ---

sns.set_style("whitegrid")
plt.figure(figsize=(20, 10))

# Vẽ biểu đồ cột cho số lượng học sinh BẤT THƯỜNG theo Lớp và Bài kiểm tra
bar_plot = sns.barplot(
    x=group_col,
    y='Count',
    hue='Test',
    data=final_plot_df,
    palette='viridis' # Sử dụng bảng màu đa dạng
)

plt.title(f'Số lượng Học sinh Bất thường (|Z| > {z_score_threshold}) theo Lớp và Từng Bài Kiểm tra', fontsize=18, fontweight='bold')
plt.xlabel('Lớp', fontsize=15)
plt.ylabel('Số lượng Học sinh Bất thường', fontsize=15)
plt.xticks(rotation=45, ha='right', fontsize=12)
plt.yticks(fontsize=12)
plt.legend(title='Bài kiểm tra', title_fontsize='13', fontsize='12')

# Thêm giá trị số lên trên cột (giúp đọc dữ liệu dễ dàng hơn)
for container in bar_plot.containers:
    bar_plot.bar_label(container, fmt='%d', padding=3, fontsize=10)

plt.tight_layout()
plt.show()

# --- 5. Tóm tắt Dữ liệu Bất thường (In ra Báo cáo) ---
print("\n--- BÁO CÁO TỔNG HỢP VỀ HỌC SINH BẤT THƯỜNG ---")

# Tính tổng số bất thường (tính cả trùng lặp, một HS có thể bất thường ở nhiều bài)
total_outliers = final_plot_df['Count'].sum()
print(f"Tổng số lần một học sinh được xác định là Bất thường (trên tất cả bài kiểm tra): {total_outliers}")

print("\n--- Danh sách Học sinh Bất thường (Top 5 cho mỗi bài kiểm tra) ---")
for col in score_cols:
    z_col = f'Z_{col}'
    outlier_col = f'Is_Outlier_{col}'

    outliers_list = df[df[outlier_col] == 'Bất thường'].sort_values(by=z_col, key=lambda x: np.abs(x), ascending=False)

    if not outliers_list.empty:
        print(f"\n* Bài kiểm tra {col} ({len(outliers_list)} HS Bất thường):")
        display_cols = ['MaHS', group_col, col, z_col]
        print(outliers_list[display_cols].head(5).to_markdown(index=False, numalign="left", stralign="left"))

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files

# ==============================================================================
# BƯỚC 1: Cấu hình và Tải dữ liệu
# ==============================================================================

# Cấu hình hiển thị đồ thị
sns.set_style("whitegrid")

# Tải file CSV từ máy tính cá nhân của bạn lên Colab
file_name = "Student_GradeSummary.csv"
print(">>> VUI LÒNG TẢI LÊN FILE 'Student_GradeSummary.csv' khi cửa sổ chọn file xuất hiện. <<<")
try:
    # Lệnh files.upload() sẽ mở cửa sổ chọn file
    uploaded = files.upload()

    if file_name in uploaded:
        # Đọc dữ liệu từ file CSV
        df = pd.read_csv(file_name)
        print(f"\n✅ Đã tải và đọc thành công file '{file_name}'.")
    else:
        print(f"❌ Lỗi: Không tìm thấy file '{file_name}' đã được tải lên.")
        exit() # Dừng chương trình nếu không tìm thấy file

except Exception as e:
    print(f"❌ Lỗi trong quá trình tải file: {e}")
    exit()

# ==============================================================================
# BƯỚC 2: Tiền xử lý dữ liệu
# ==============================================================================

# 1. Đổi tên cột để dễ làm việc hơn
column_mapping = {
    'STT': 'stt', 'MaHS': 'mahs', 'lop': 'lop', 'Toan': 'toan',
    'Van': 'van', 'Ly': 'ly', 'Hoa': 'hoa', 'Ngoaingu': 'ngoaingu',
    'Su': 'su', 'Tin': 'tin', 'Sinh': 'sinh', 'Dia': 'dia'
}
df = df.rename(columns=column_mapping)

# 2. Xác định các cột điểm
score_cols = ['toan', 'van', 'ly', 'hoa', 'ngoaingu', 'su', 'tin', 'sinh', 'dia']

# 3. Chuyển đổi các cột điểm sang kiểu số (numeric), lỗi sẽ được gán là NaN
for col in score_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

print("\n--- 5 Dòng dữ liệu sau khi tiền xử lý ---")
print(df.head())


# ==============================================================================
# BƯỚC 3: Tính Toán Z-score và Xác định Giá trị Bất thường
# ==============================================================================

def calculate_zscore_and_outliers(data, score_cols):
    """
    Tính Z-score cho từng môn học, chia theo lớp, và xác định giá trị bất thường.
    Outlier được định nghĩa là |Z-score| > 2.
    """
    df_result = data.copy()

    # Tạo các cột mới để lưu Z-score và cờ Outlier
    for col in score_cols:
        df_result[f'{col}_ZScore'] = np.nan
        df_result[f'{col}_IsOutlier'] = False

    # Lặp qua từng lớp để tính toán riêng biệt (phân tích theo nhóm)
    for lop in df_result['lop'].unique():
        class_data = df_result[df_result['lop'] == lop]

        for col in score_cols:
            # 1. Tính Mean (Trung bình) và Standard Deviation (Độ lệch chuẩn) TRONG LỚP đó
            mean = class_data[col].mean()
            std = class_data[col].std()

            # 2. Tính Z-score: Z = (X - Mean) / Std
            if std > 0:
                z_score = (class_data[col] - mean) / std
            else:
                # Trường hợp đặc biệt: Std = 0 (tất cả điểm bằng nhau), Z-score = 0
                z_score = 0
                z_score[class_data[col].isna()] = np.nan # Giữ NaN cho các điểm thiếu

            # 3. Gán kết quả vào DataFrame
            df_result.loc[df_result['lop'] == lop, f'{col}_ZScore'] = z_score

            # 4. Xác định Outlier: |Z-score| > 2
            outlier_mask = z_score.abs() > 2
            df_result.loc[df_result['lop'] == lop, f'{col}_IsOutlier'] = outlier_mask

    return df_result

# Thực hiện tính toán
df_zscore = calculate_zscore_and_outliers(df, score_cols)

print("\n--- Kết quả Z-score và Outlier (5 Dòng đầu tiên) ---")
# Chỉ hiển thị các cột liên quan
cols_to_show = ['lop', 'mahs'] + [c for c in df_zscore.columns if 'ZScore' in c or 'IsOutlier' in c]
print(df_zscore[cols_to_show].head())

# Hiển thị tổng số giá trị bất thường tìm thấy
total_outliers = df_zscore[[c for c in df_zscore.columns if 'IsOutlier' in c]].sum().sum()
print(f"\n🎉 Tổng số giá trị bất thường (|Z| > 2) tìm thấy trên tất cả các môn: {int(total_outliers)}")

# ==============================================================================
# BƯỚC 4: Trực Quan Hóa (Biểu đồ Cột)
# ==============================================================================

# Chuẩn bị dữ liệu tổng hợp số lượng Outlier
outlier_counts = {}
for col in score_cols:
    outlier_col = f'{col}_IsOutlier'
    # Nhóm theo lớp và đếm số lượng True (Outlier)
    counts = df_zscore.groupby('lop')[outlier_col].sum()
    outlier_counts[col] = counts

df_outliers_summary = pd.DataFrame(outlier_counts).fillna(0).astype(int)
df_outliers_summary = df_outliers_summary.T # Chuyển vị để môn học là index, lớp là cột

print("\n--- Bảng tổng hợp số lượng giá trị bất thường (Outlier) ---")
print(df_outliers_summary)


# Tạo Biểu đồ Cột (Bar Plot)
plt.figure(figsize=(18, 8))

# Sử dụng 'melt' để chuyển DataFrame về dạng dài (long format)
df_plot = df_outliers_summary.reset_index().rename(columns={'index': 'Môn học'})
df_plot_melted = df_plot.melt(id_vars='Môn học', var_name='Lớp', value_name='Số lượng Outlier')

# Vẽ biểu đồ cột
ax = sns.barplot(x='Môn học', y='Số lượng Outlier', hue='Lớp', data=df_plot_melted, palette='viridis')

# Thiết lập tiêu đề và nhãn
plt.title('Số lượng Giá trị Bất thường (|Z| > 2) theo Môn học và Lớp', fontsize=16)
plt.xlabel('Môn học', fontsize=12)
plt.ylabel('Số lượng Học sinh có điểm bất thường', fontsize=12)
plt.xticks(rotation=45, ha='right')

# Thêm giá trị số lên trên cột
for p in ax.patches:
    height = p.get_height()
    if height > 0:
        ax.annotate(f'{int(height)}',
                    (p.get_x() + p.get_width() / 2., height),
                    ha='center', va='center',
                    xytext=(0, 9),
                    textcoords='offset points',
                    fontsize=10)

plt.legend(title='Lớp', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

